
language: cpp

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-trusty-7.0
    packages:
     - ninja-build
     # TODO: These should really be the snapshots packages, but they are currently
     # broken. Remove the '-9' once they get fixed (see issue #642 for more info)
     - llvm-9-dev
     - llvm-9-tools
     - libclang-9-dev
     - clang-9

before_install:
 # Install a supported cmake version (>= 3.4.3)
 - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh 
 - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local

 # Absolute paths to LLVM's root and bin directory
 - ROOT_PATH=`llvm-config-7.0 --prefix`
 - BIN_PATH=`llvm-config-7.0 --bindir`

script:
# Build IWYU
 - mkdir build
 - cd build
 - cmake -GNinja -DCMAKE_PREFIX_PATH=$ROOT_PATH -DCMAKE_C_COMPILER=$BIN_PATH/clang -DCMAKE_CXX_COMPILER=$BIN_PATH/clang++ -DCMAKE_INSTALL_PREFIX=./ ../
 - ninja install

# Test IWYU
 - cd ..
 - python run_iwyu_tests.py -- build/bin/include-what-you-use
 - python fix_includes_test.py
 - python iwyu_tool_test.py
